config:
  DAY: "85"

bankapp:
  replicaCount: 2

  image:
    tag: latest

  autoscaling:
    enabled: false

mysql:
  persistence:
    size: 2Gi
    storageClass: gp2

ollama:
  persistence:
    size: 5Gi
    storageClass: gp2
