apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bankapp.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | b64enc }}
  MYSQL_USER: {{ .Values.secrets.mysqlUser | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | b64enc }}
